# Generated by Django 2.2.7 on 2019-11-22 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('desc', models.CharField(max_length=500)),
                ('brand', models.CharField(default='NA', max_length=50)),
                ('pprice', models.IntegerField(default=0)),
                ('price', models.IntegerField()),
            ],
        ),
    ]
